name: 'Verify the generated code is compilable'
description: 'Verifies the generated code is compilable and executable'
outputs:
  compile_status:
    description: 'Compilation status'
    value: ${{ steps.verify.outputs.compile_status }}
  compile_error:
    description: 'Compilation error message'
    value: ${{ steps.verify.outputs.compile_error }}
runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
      id: setup

    - name: Install dependencies
      run: go mod tidy
      shell: bash

    - name: Verify compilation
      id: verify
      run: |
        set +e  # Don't exit immediately on error
        OUTPUT=$(go build ./spec/http1.1 2>&1)
        EXIT_CODE=$?
        if [ $EXIT_CODE -eq 0 ]; then
          echo "Compilation successful!"
          echo "compile_status=success" >> $GITHUB_OUTPUT
          echo "compile_error=" >> $GITHUB_OUTPUT
        else
          echo "Compilation failed!"
          echo "compile_status=failure" >> $GITHUB_OUTPUT
          echo "compile_error<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi
      shell: bash
