name: 'Verify the generated code is compilable'
description: 'Verifies the generated code is compilable and executable'
outputs:
  result:
    description: 'The verification result'
    value: ${{ steps.verify.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
      id: setup

    - name: Install dependencies
      run: go mod tidy
      shell: bash

    - name: Verify compilation
      id: verify
      run: |
        set -e
        # Attempt to build the code
        go build ./spec/http1.1 && echo "Compilation successful!" || (echo "Compilation failed!" && exit 1)
        echo "Compilation successful!"
        echo "result=success" >> $GITHUB_OUTPUT
      shell: bash
