name: HTTP/1.1 Test Case
description: Create a new HTTP/1.1 test case
title: "[Test Case] HTTP/1.1: Request for a new test case - <Test Case Name>"
labels: 
  - test-case
  - http1.1
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a new test case! Please fill out the information below.

  - type: input
    id: rfc-document
    attributes:
      label: RFC Document
      description: Which RFC document is this test case based on?
      placeholder: e.g., RFC 7230
    validations:
      required: true

  - type: input
    id: rfc-section
    attributes:
      label: RFC Section
      description: Which section of the RFC is this test case related to?
      placeholder: e.g., Section 3.3.2
    validations:
      required: true

  - type: input
    id: rfc-link
    attributes:
      label: RFC Link
      description: Provide a link to the relevant RFC section, if available.
      placeholder: https://tools.ietf.org/html/rfc7230#section-3.3.2

  - type: textarea
    id: test-case-name
    attributes:
      label: Test Case Name
      description: Enter a concise name for the test case
      placeholder: e.g., Invalid HTTP Version Format
    validations:
      required: true

  - type: textarea
    id: test-case-description
    attributes:
      label: Test Case Description
      description: Briefly describe the test case
      placeholder: This test case verifies the server's response to an invalid HTTP version format in the request line.
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Mode
      description: Select the compliance level for this test case
      options:
        - MUST
        - SHOULD
        - MAY
    validations:
      required: true

  - type: textarea
    id: sample-request
    attributes:
      label: Sample Request
      description: Provide the HTTP request for this test case
      placeholder: |
        GET / HTTP/1.0
        Host: example.com
    validations:
      required: true

  - type: input
    id: expected-status-code
    attributes:
      label: Expected Status Code
      description: What is the expected HTTP status code in the response?
      placeholder: e.g., 400
    validations:
      required: true

  - type: textarea
    id: expected-headers
    attributes:
      label: Expected Headers
      description: List any specific headers expected in the response
      placeholder: |
        Content-Type: text/plain
        Connection: close

  - type: textarea
    id: expected-body
    attributes:
      label: Expected Body
      description: Describe the expected body in the response, if any
      placeholder: The response body should contain an error message
  