name: 'Check Authorized User'
description: 'Verifies if the user is authorized to trigger the workflow'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  authorized-users:
    description: 'Comma-separated list of authorized GitHub usernames'
    required: true
  user-login:
    description: 'GitHub username to check'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check authorized user
      shell: bash
      run: |
        IFS=',' read -ra AUTH_USERS <<< "${{ inputs.authorized-users }}"
        for user in "${AUTH_USERS[@]}"; do
          if [[ "$user" == "${{ inputs.user-login }}" ]]; then
            echo "User ${{ inputs.user-login }} is authorized"
            exit 0
          fi
        done
        echo "User ${{ inputs.user-login }} is not authorized"
        exit 1
